version: '3.9'

services:
  database: 
    image: postgres
    container_name: teste
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Postgres
    volumes:
       - /var/lib/postgresql/data


volumes:
  pgdata:
    driver: local